# Generated by Django 5.0.6 on 2024-06-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_producto', models.CharField(max_length=45)),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
