# Generated by Django 5.0.6 on 2024-06-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Marca',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
